# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 155d5e95b4ea187f678f0cd15e6843e2af3f9d41461cd71a62ce0689690ca7c3140e130eaae08ee5699dda53ab588188900053a1a968db40e983f0e5a3655206

test:
  secret_key_base: db782fb7a22f94ea498dce6d8a77f823d1b38b7025d220d1008c399b4ec0134a78cc1020b8993a7e004a2dcc2e5efc411898e8db75ae81dceb9778638ee5659a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
